controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\TestController::index
product:
    path: /product
    controller: App\Controller\ProductController::product